(() => {
  "use strict";
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const STORAGE={preferences:"fitai_preferences_v2",saved:"fitai_saved_v2"};
  const state={photoDataUrl:"",preferences:{gender:"",styles:[],colors:[],budget:3000,occasions:[],fit:""},lastFits:[],generating:false};
  const esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const money=v=>`₹${Number(v||0).toLocaleString("en-IN")}`;
  const parse=(v,f)=>{try{return v?JSON.parse(v):f}catch{return f}};
  const status=(m,id="#status")=>{const e=$(id);if(e)e.textContent=m};
  function sync(){const group=n=>$(`.choice-group[data-group="${n}"]`);const one=n=>{const g=group(n);return g?$(".choice.active",g)?.textContent.trim()||"":""};const many=n=>{const g=group(n);return g?$$('.choice.active',g).map(x=>x.textContent.trim()):[]};const bg=group("budget"),bb=bg?$(".choice.active",bg):null;state.preferences={gender:one("gender"),styles:many("styles"),colors:many("colors"),budget:Number(bb?.dataset.value||$("#budget")?.value||3000),occasions:many("occasions"),fit:one("fit")};return state.preferences}
  function steps(n){$$('.steps span').forEach((x,i)=>x.classList.toggle('active',i<n))}
  document.addEventListener("click",e=>{const b=e.target.closest('.choice-group .choice');if(!b)return;e.preventDefault();const g=b.closest('.choice-group');if(g.classList.contains('multi'))b.classList.toggle('active');else{$$('.choice',g).forEach(x=>x.classList.remove('active'));b.classList.add('active')}sync();steps(2)});
  document.addEventListener("click",e=>{const b=e.target.closest('#styleChips .chip');if(!b)return;e.preventDefault();$$('#styleChips .chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');const s=$('#style');if(s&&[...s.options].some(o=>o.value===b.textContent.trim()))s.value=b.textContent.trim()});
  document.addEventListener("click",e=>{const b=e.target.closest('[data-scroll]');if(!b)return;e.preventDefault();$(b.dataset.scroll)?.scrollIntoView({behavior:'smooth'})});
  $('#savePreferences')?.addEventListener('click',e=>{e.preventDefault();sync();localStorage.setItem(STORAGE.preferences,JSON.stringify(state.preferences));status('✓ Your style has been saved.','#preferenceStatus')});
  const photoInput=$('#photoInput');
  photoInput?.addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)){alert('Please choose a JPG, PNG or WebP image.');e.target.value='';return}if(f.size>7*1024*1024){alert('Please choose an image under 7MB.');e.target.value='';return}const reader=new FileReader();reader.onload=()=>{state.photoDataUrl=String(reader.result||'');const p=$('#preview');if(p){p.src=state.photoDataUrl;p.style.display='block'}const i=$('#photoInfo');if(i)i.textContent=`${f.name} · ${(f.size/1024/1024).toFixed(1)} MB`;$('#removePhoto')?.classList.remove('hidden');steps(1)};reader.readAsDataURL(f)});
  $('#removePhoto')?.addEventListener('click',e=>{e.preventDefault();state.photoDataUrl='';if(photoInput)photoInput.value='';const p=$('#preview');if(p){p.removeAttribute('src');p.style.display='none'}const i=$('#photoInfo');if(i)i.textContent='';$('#removePhoto')?.classList.add('hidden')});
  function quick(){return{style:$('#style')?.value||'Streetwear',occasion:$('#occasion')?.value||'Casual',budget:Number($('#budget')?.value||3000)}}
  function item(x){if(!x)return null;if(typeof x==='string')return{name:x,price:0,search_query:x};return{name:String(x.name||'').trim(),price:Number(x.price||0),search_query:String(x.search_query||x.name||'').trim()}}
  function normalize(f,i){return{...f,name:String(f.name||`FITAI Look ${i+1}`),emoji:String(f.emoji||['🖤','🤍','🕶️'][i]||'✨'),match:Math.max(70,Math.min(99,Number(f.match)||90)),total_price:Number(f.total_price||f.price||0),shirt:item(f.shirt),pant:item(f.pant),shoes:item(f.shoes),accessory:item(f.accessory)}}
  function addCSS(){if($('#fitai-extra-css'))return;const s=document.createElement('style');s.id='fitai-extra-css';s.textContent=`.fitai-loading{text-align:center;padding:42px 20px}.fitai-spinner{width:34px;height:34px;border:3px solid #2b2b30;border-top-color:#d9ff5a;border-radius:50%;margin:0 auto 16px;animation:fitaiSpin .8s linear infinite}@keyframes fitaiSpin{to{transform:rotate(360deg)}}#generateBtn[disabled]{opacity:.65;cursor:wait}.fitai-piece-list{display:grid;gap:8px;margin:14px 0}.fitai-piece{display:grid;grid-template-columns:30px 1fr auto;align-items:center;gap:8px;background:#101012;border:1px solid #2b2b30;border-radius:12px;padding:9px}.fitai-piece div{display:grid}.fitai-piece strong{font-size:13px}.fitai-piece span{font-size:20px}.fitai-piece>b{color:#d9ff5a;font-size:12px}`;document.head.appendChild(s)}
  function loading(on){const b=$('#generateBtn'),r=$('#results');if(on){if(b){b.disabled=true;b.dataset.old=b.textContent;b.textContent='✦ Styling your outfit…';b.setAttribute('aria-busy','true')}steps(3);status('✦ FITAI is styling you… please wait');if(r){r.innerHTML='<div class="panel fitai-loading"><div class="fitai-spinner"></div><b>FITAI is styling you…</b><p class="muted">Matching your style, fit, occasion and budget.</p><small class="muted">Your results will appear here automatically.</small></div>';requestAnimationFrame(()=>r.scrollIntoView({behavior:'smooth',block:'start'}))}}else{if(b){b.disabled=false;b.textContent=b.dataset.old||'✦ Style me with AI';b.removeAttribute('aria-busy')}}}
  async function generateAI(){if(state.generating)return;state.generating=true;addCSS();const p=sync(),q=quick(),r=$('#results');loading(true);try{const response=await fetch('/api/stylist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({preferences:{...p,quickStyle:q.style,quickOccasion:q.occasion,budget:p.budget||q.budget},photoDataUrl:state.photoDataUrl||''})});const data=await response.json().catch(()=>({}));if(!response.ok||!Array.isArray(data.looks))throw new Error(data.error||'AI could not generate your outfit.');state.lastFits=data.looks.map(normalize);render(state.lastFits);steps(4);status(`✦ ${state.lastFits.length} AI-styled complete outfits ready.`);requestAnimationFrame(()=>r?.scrollIntoView({behavior:'smooth',block:'start'}))}catch(err){console.error('FITAI generation error',err);const msg=err?.message||'Something went wrong. Please try again.';status(`⚠ ${msg}`);if(r){r.innerHTML=`<div class="panel"><b>AI styling couldn't be completed.</b><p class="muted">${esc(msg)}</p><button type="button" class="primary" id="retryAI">↻ Try again</button></div>`;requestAnimationFrame(()=>r.scrollIntoView({behavior:'smooth',block:'start'}));$('#retryAI')?.addEventListener('click',generateAI)}}finally{state.generating=false;loading(false)}}
  $('#generateBtn')?.addEventListener('click',e=>{e.preventDefault();generateAI()});
  function piece(icon,label,x){if(!x?.name)return'';return`<div class="fitai-piece"><span>${icon}</span><div><small class="muted">${label}</small><strong>${esc(x.name)}</strong></div><b>${x.price?money(x.price):''}</b></div>`}
  function render(fits){const r=$('#results');if(!r)return;addCSS();r.innerHTML=fits.map((f,i)=>`<article class="outfit"><div class="outfit-visual" aria-hidden="true">${esc(f.emoji)}</div><div class="outfit-body"><small class="muted">AI MATCH · ${f.match}% · ${esc(f.style||'Personalized')}</small><h3>${esc(f.name)}</h3><p class="muted">${esc(f.reason||'Built around your preferences and proportions.')}</p><div class="fitai-piece-list">${piece('👕','Shirt / Top',f.shirt)}${piece('👖','Pant / Bottom',f.pant)}${piece('👟','Shoes',f.shoes)}${piece('🧢','Accessory',f.accessory)}</div><div class="price">${money(f.total_price)}</div><div class="actions"><button type="button" data-save="${i}">♡ Save</button><button type="button" data-remix="${i}">↻ Remix</button><button type="button" data-shop="${i}">Shop this look →</button></div></div></article>`).join('');bindResults(fits)}
  function shopURL(site,q){return site==='amazon'?`https://www.amazon.in/s?k=${encodeURIComponent(q)}`:`https://www.flipkart.com/search?q=${encodeURIComponent(q)}`}
  function shop(f){const old=$('#fitaiShopModal');if(old)old.remove();const m=document.createElement('div');m.id='fitaiShopModal';m.style.cssText='position:fixed;inset:0;z-index:99999;display:flex;align-items:center;justify-content:center;padding:18px;background:#000c;backdrop-filter:blur(8px)';const parts=[['👕','SHIRT / TOP',f.shirt],['👖','PANT / BOTTOM',f.pant],['👟','SHOES',f.shoes],['🧢','ACCESSORY',f.accessory]].filter(x=>x[2]?.name);m.innerHTML=`<div style="width:min(920px,96vw);max-height:90vh;overflow:auto;background:#141416;color:#f4f4f0;border:1px solid #2b2b30;border-radius:24px;padding:26px;position:relative"><button id="closeShop" style="position:absolute;right:14px;top:8px;border:0;background:none;color:#aaa;font-size:30px">×</button><p class="eyebrow">SHOP THIS EXACT OUTFIT</p><h2>${esc(f.name)}</h2><p class="muted">One exact piece for every part of the outfit. No alternatives.</p><b style="color:#d9ff5a">Estimated total · ${money(f.total_price)}</b><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:20px">${parts.map(([ic,l,x])=>`<article style="background:#1a1a1d;border:1px solid #2b2b30;border-radius:18px;padding:16px;display:flex;flex-direction:column;min-height:190px"><div style="font-size:34px">${ic}</div><small class="muted">${l}</small><h3>${esc(x.name)}</h3><b style="color:#d9ff5a;margin-bottom:12px">${x.price?money(x.price):'Price varies'}</b><div style="display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:auto"><a href="${shopURL('amazon',x.search_query||x.name)}" target="_blank" rel="noopener noreferrer" style="padding:10px;text-align:center;text-decoration:none;border-radius:10px;background:#0f0f11;color:#f4f4f0">Amazon ↗</a><a href="${shopURL('flipkart',x.search_query||x.name)}" target="_blank" rel="noopener noreferrer" style="padding:10px;text-align:center;text-decoration:none;border-radius:10px;background:#0f0f11;color:#f4f4f0">Flipkart ↗</a></div></article>`).join('')}</div></div>`;document.body.appendChild(m);$('#closeShop',m).onclick=()=>m.remove();m.onclick=e=>{if(e.target===m)m.remove()}}
  function bindResults(fits){$$('[data-save]',$('#results')).forEach(b=>b.onclick=()=>{const f=fits[+b.dataset.save],saved=parse(localStorage.getItem(STORAGE.saved),[]);if(!saved.some(x=>x.name===f.name))saved.push(f);localStorage.setItem(STORAGE.saved,JSON.stringify(saved.slice(-12)));b.textContent='✓ Saved';renderSaved()});$$('[data-remix]',$('#results')).forEach(b=>b.onclick=()=>generateAI());$$('[data-shop]',$('#results')).forEach(b=>b.onclick=()=>shop(fits[+b.dataset.shop]))}
  function renderSaved(){const w=$('#savedLooks');if(!w)return;const saved=parse(localStorage.getItem(STORAGE.saved),[]);w.innerHTML=saved.length?saved.map((f,i)=>`<article class="saved-card"><span>${esc(f.emoji||'✨')}</span><div><b>${esc(f.name)}</b><small>${money(f.total_price)}</small></div><button type="button" data-del="${i}">×</button></article>`).join(''):'<p class="muted">No saved outfits yet. Generate a look and tap Save.</p>';$$('[data-del]',w).forEach(b=>b.onclick=()=>{const s=parse(localStorage.getItem(STORAGE.saved),[]);s.splice(+b.dataset.del,1);localStorage.setItem(STORAGE.saved,JSON.stringify(s));renderSaved()})}
  const saved=parse(localStorage.getItem(STORAGE.preferences),null);if(saved){state.preferences=saved;}
  renderSaved();
})();
