(()=>{
"use strict";
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const K={p:"fitai_preferences_v2",s:"fitai_saved_v2",u:"fitai_demo_user_v2"};
const state={photo:"",fits:[],busy:false,prefs:{gender:"",styles:[],colors:[],budget:3000,occasions:[],fit:""}};
const esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>`₹${Number(v||0).toLocaleString('en-IN')}`;
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'')}catch{return f}};
const msg=(x,id='#status')=>{const e=$(id);if(e)e.textContent=x};
function sync(){const g=n=>$(`.choice-group[data-group="${n}"]`),one=n=>g(n)?$('.choice.active',g(n))?.textContent.trim()||'':'',many=n=>g(n)?$$('.choice.active',g(n)).map(x=>x.textContent.trim()):[];const b=g('budget')?$('.choice.active',g('budget')):null;state.prefs={gender:one('gender'),styles:many('styles'),colors:many('colors'),budget:Number(b?.dataset.value||$('#budget')?.value||3000),occasions:many('occasions'),fit:one('fit')};return state.prefs}
function steps(n){$$('.steps span').forEach((x,i)=>x.classList.toggle('active',i<n))}
document.addEventListener('click',e=>{const b=e.target.closest('.choice-group .choice');if(b){e.preventDefault();const g=b.closest('.choice-group');if(g.classList.contains('multi'))b.classList.toggle('active');else{$$('.choice',g).forEach(x=>x.classList.remove('active'));b.classList.add('active')}sync();steps(2);return}const c=e.target.closest('#styleChips .chip');if(c){e.preventDefault();$$('#styleChips .chip').forEach(x=>x.classList.remove('active'));c.classList.add('active');if($('#style'))$('#style').value=c.textContent.trim();return}const sc=e.target.closest('[data-scroll]');if(sc){e.preventDefault();$(sc.dataset.scroll)?.scrollIntoView({behavior:'smooth'});return}});
$('#savePreferences')?.addEventListener('click',e=>{e.preventDefault();sync();localStorage.setItem(K.p,JSON.stringify(state.prefs));msg('✓ Your style has been saved.','#preferenceStatus')});
$('#clearPreferences')?.addEventListener('click',e=>{e.preventDefault();localStorage.removeItem(K.p);state.prefs={gender:'',styles:[],colors:[],budget:3000,occasions:[],fit:''};$$('.choice').forEach(x=>x.classList.remove('active'));$('.choice-group[data-group="budget"] .choice[data-value="3000"]')?.classList.add('active');msg('Preferences reset.','#preferenceStatus')});
function compress(file){return new Promise(resolve=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const max=900,scale=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);c.getContext('2d').drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.68))};im.onerror=()=>resolve('');im.src=String(r.result)};r.onerror=()=>resolve('');r.readAsDataURL(file)})}
$('#photoInput')?.addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>8*1024*1024){alert('Please choose a JPG, PNG or WebP image under 8MB.');e.target.value='';return}state.photo=await compress(f);if($('#preview')){$('#preview').src=state.photo;$('#preview').style.display='block'}if($('#photoInfo'))$('#photoInfo').textContent=`${f.name} · ${(f.size/1024/1024).toFixed(1)} MB`;$('#removePhoto')?.classList.remove('hidden');steps(1)});
$('#removePhoto')?.addEventListener('click',e=>{e.preventDefault();state.photo='';if($('#photoInput'))$('#photoInput').value='';if($('#preview')){$('#preview').removeAttribute('src');$('#preview').style.display='none'}if($('#photoInfo'))$('#photoInfo').textContent='';$('#removePhoto').classList.add('hidden')});
function quick(){return{style:$('#style')?.value||'Streetwear',occasion:$('#occasion')?.value||'Casual',budget:Number($('#budget')?.value||3000)}}
function fallback(p){const c=p.colors[0]||'Black',sets=[['Essential','🖤',`${c} relaxed-fit cotton shirt`,750,'Straight-fit black trousers',900,'Minimal white sneakers',850],['Clean Fit','🤍','Cream oversized textured shirt',850,'Dark straight-fit jeans',950,'Black low-top sneakers',800],['Statement Fit','🕶️','Oversized graphic tee',650,'Wide-leg cargo pants',950,'Retro chunky sneakers',900]];return sets.map((x,i)=>({name:`${p.style} ${x[0]}`,emoji:x[1],match:92-i*3,style:p.style,occasion:p.occasion,fit:p.fit,total_price:Math.min(x[3]+x[5]+x[7],p.budget),reason:`A complete ${p.style} look for ${p.occasion.toLowerCase()} with a ${p.fit.toLowerCase()} silhouette.`,shirt:{name:x[2],price:x[3],search_query:x[2]},pant:{name:x[4],price:x[5],search_query:x[4]},shoes:{name:x[6],price:x[7],search_query:x[6]},accessory:null}))}
function render(fits){const r=$('#results');if(!r)return;r.innerHTML=fits.map((f,i)=>`<article class="outfit"><div class="outfit-visual" aria-hidden="true">${esc(f.emoji||'✨')}</div><div class="outfit-body"><small class="muted">AI MATCH · ${f.match||90}% · ${esc(f.style||'Personalized')}</small><h3>${esc(f.name)}</h3><p class="muted">${esc(f.reason||'Built around your preferences.')}</p><div class="fitai-pieces"><div>👕 <b>Shirt / Top</b><span>${esc(f.shirt?.name||'')}</span></div><div>👖 <b>Pant / Bottom</b><span>${esc(f.pant?.name||'')}</span></div><div>👟 <b>Shoes</b><span>${esc(f.shoes?.name||'')}</span></div></div><div class="price">${money(f.total_price)}</div><div class="actions"><button type="button" data-save="${i}">♡ Save</button><button type="button" data-remix="${i}">↻ Remix</button><button type="button" data-shop="${i}">Shop this look →</button></div></div></article>`).join('');bind(fits)}
function shop(f){const m=document.createElement('div');m.id='fitaiShopModal';m.style.cssText='position:fixed;inset:0;z-index:99999;display:flex;align-items:center;justify-content:center;padding:18px;background:#000c';const a=[['👕','SHIRT / TOP',f.shirt],['👖','PANT / BOTTOM',f.pant],['👟','SHOES',f.shoes],['🧢','ACCESSORY',f.accessory]].filter(x=>x[2]?.name);m.innerHTML=`<div class="fitai-shop"><button id="closeShop">×</button><p class="eyebrow">SHOP THIS EXACT OUTFIT</p><h2>${esc(f.name)}</h2><p class="muted">One exact piece for every part. No alternatives.</p><b class="price">Estimated total · ${money(f.total_price)}</b><div class="fitai-shop-grid">${a.map(x=>`<article><strong>${x[0]} ${x[1]}</strong><h3>${esc(x[2].name)}</h3><span class="price">${x[2].price?money(x[2].price):'Price varies'}</span><div><a target="_blank" rel="noopener" href="https://www.amazon.in/s?k=${encodeURIComponent(x[2].search_query||x[2].name)}">Amazon ↗</a><a target="_blank" rel="noopener" href="https://www.flipkart.com/search?q=${encodeURIComponent(x[2].search_query||x[2].name)}">Flipkart ↗</a></div></article>`).join('')}</div></div>`;document.body.appendChild(m);$('#closeShop',m).onclick=()=>m.remove();m.onclick=e=>{if(e.target===m)m.remove()}}
function bind(fits){$$('[data-save]',$('#results')).forEach(b=>b.onclick=()=>{const f=fits[+b.dataset.save],a=read(K.s,[]);if(!a.some(x=>x.name===f.name))a.push(f);localStorage.setItem(K.s,JSON.stringify(a.slice(-12)));b.textContent='✓ Saved';renderSaved()});$$('[data-shop]',$('#results')).forEach(b=>b.onclick=()=>shop(fits[+b.dataset.shop]));$$('[data-remix]',$('#results')).forEach(b=>b.onclick=()=>generate(true))}
function renderSaved(){const w=$('#savedList');if(!w)return;const a=read(K.s,[]);w.innerHTML=a.length?a.slice().reverse().map((f,i)=>`<article class="panel saved-card"><div><b>${esc(f.name)}</b><p class="muted">${esc(f.shirt?.name||'')} · ${esc(f.pant?.name||'')} · ${esc(f.shoes?.name||'')}</p><span class="price">${money(f.total_price)}</span></div><button class="outline" data-remove-saved="${i}">Remove</button></article>`).join(''):'<p class="muted">No saved outfits yet. Generate a look and tap Save.</p>';$$('[data-remove-saved]',w).forEach(b=>b.onclick=()=>{const a=read(K.s,[]).slice().reverse();a.splice(+b.dataset.removeSaved,1);localStorage.setItem(K.s,JSON.stringify(a.reverse()));renderSaved()})}
document.addEventListener('click',e=>{const b=e.target.closest('[data-remove-saved]');if(b){e.preventDefault();return}if(e.target.closest('#clearSaved')){localStorage.removeItem(K.s);renderSaved();$('#clearSaved')?.classList.add('hidden')}});
async function generate(remix=false){if(state.busy)return;state.busy=true;const b=$('#generateBtn'),r=$('#results'),p=sync(),q=quick(),instant=fallback({...p,style:q.style,occasion:q.occasion});if(b){b.disabled=true;b.dataset.old=b.textContent;b.textContent='✦ Styling…';b.setAttribute('aria-busy','true')}steps(3);msg('✦ FITAI is styling you…');if(r){r.innerHTML='<div class="panel fitai-loading"><div class="fitai-spinner"></div><b>FITAI is styling you…</b><p class="muted">Your outfit will appear here automatically.</p></div>';requestAnimationFrame(()=>r.scrollIntoView({behavior:'smooth',block:'start'}))}
// Never leave the user waiting: instant local styling appears after 2.8s even if the AI/network is slow.
let shown=false;const showInstant=()=>{if(shown)return;shown=true;state.fits=instant;render(instant);steps(4);msg('✦ Instant personalized looks ready. AI will replace them if its response arrives soon.')};const fallbackTimer=setTimeout(showInstant,2800);
try{const controller=new AbortController();const stop=setTimeout(()=>controller.abort(),6000);const response=await fetch('/api/stylist',{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({preferences:{...p,quickStyle:q.style,quickOccasion:q.occasion,budget:p.budget||q.budget},photoDataUrl:state.photo})});clearTimeout(stop);const data=await response.json().catch(()=>({}));clearTimeout(fallbackTimer);if(Array.isArray(data.looks)){state.fits=data.looks;render(data.looks);steps(4);msg(data.source==='ai'?'✦ AI-personalized looks ready.':'✦ Personalized looks ready.')}else if(!shown)throw Error(data.error||'AI response unavailable');}catch(e){clearTimeout(fallbackTimer);console.error(e);if(!shown)showInstant();}finally{state.busy=false;if(b){b.disabled=false;b.textContent=b.dataset.old||'✦ Style me with AI';b.removeAttribute('aria-busy')}}}
$('#generateBtn')?.addEventListener('click',e=>{e.preventDefault();generate()});
const savedPrefs=read(K.p,null);if(savedPrefs){state.prefs=savedPrefs;const g=n=>$(`.choice-group[data-group="${n}"]`);const act=(n,v)=>{if(!g(n))return;$$('.choice',g(n)).forEach(x=>{if(n==='budget'?Number(x.dataset.value)===Number(v):Array.isArray(v)?v.includes(x.textContent.trim()):x.textContent.trim()===v)x.classList.add('active')})};act('gender',savedPrefs.gender);act('styles',savedPrefs.styles);act('colors',savedPrefs.colors);act('budget',savedPrefs.budget);act('occasions',savedPrefs.occasions);act('fit',savedPrefs.fit)}
renderSaved();
const css=document.createElement('style');css.textContent=`.fitai-loading{text-align:center;padding:40px}.fitai-spinner{width:34px;height:34px;border:3px solid #2b2b30;border-top-color:#d9ff5a;border-radius:50%;margin:0 auto 15px;animation:spin .8s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}.fitai-pieces{display:grid;gap:7px;margin:14px 0}.fitai-pieces div{display:grid;grid-template-columns:28px 1fr;padding:9px;background:#101012;border:1px solid #2b2b30;border-radius:11px}.fitai-pieces div b{grid-column:2;font-size:11px;color:#a5a5aa}.fitai-pieces div span{grid-column:2}.fitai-shop{width:min(900px,95vw);max-height:90vh;overflow:auto;background:#141416;color:#f4f4f0;border:1px solid #2b2b30;border-radius:24px;padding:25px;position:relative}.fitai-shop>button{position:absolute;right:15px;top:8px;border:0;background:none;color:#aaa;font-size:30px}.fitai-shop-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:20px}.fitai-shop-grid article{background:#1a1a1d;border:1px solid #2b2b30;border-radius:17px;padding:16px}.fitai-shop-grid article div{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:15px}.fitai-shop-grid a{padding:9px;text-align:center;background:#0f0f11;border-radius:9px;font-size:12px}@media(max-width:700px){.fitai-shop-grid{grid-template-columns:1fr}}`;document.head.appendChild(css);
})();
