export const config = { runtime: "nodejs" };
const MODEL = process.env.FITAI_OPENAI_MODEL || "gpt-4.1-mini";
const json = (data, status=200) => new Response(JSON.stringify(data), {status, headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
const s = (v,d="") => String(v ?? d).trim().slice(0,240);
function prefs(x={}) { const b=Number(x.budget); return {style:s(x.quickStyle,x.styles?.[0]||"Streetwear"), occasion:s(x.quickOccasion,x.occasions?.[0]||"Casual"), fit:s(x.fit,"Relaxed"), colors:Array.isArray(x.colors)?x.colors.slice(0,3).map(s):[], budget:Number.isFinite(b)&&b>0?b:3000}; }
function fallback(p){ const c=p.colors[0]||"Black"; const sets=[
 {name:`${p.style} Essential`,emoji:"🖤",shirt:{name:`${c} relaxed-fit cotton shirt`,price:850},pant:{name:"Straight-fit black trousers",price:1050},shoes:{name:"Minimal white sneakers",price:900}},
 {name:`${p.style} Clean Fit`,emoji:"🤍",shirt:{name:"Cream oversized textured shirt",price:950},pant:{name:"Dark straight-fit jeans",price:1100},shoes:{name:"Black low-top sneakers",price:850}},
 {name:`${p.style} Statement Fit`,emoji:"🕶️",shirt:{name:"Oversized graphic tee",price:700},pant:{name:"Wide-leg cargo pants",price:1150},shoes:{name:"Retro chunky sneakers",price:1050}}
 ]; return sets.map((x,i)=>({...x,match:94-i*3,style:p.style,occasion:p.occasion,fit:p.fit,total_price:Math.min(x.shirt.price+x.pant.price+x.shoes.price,p.budget),reason:`One complete ${p.style} ${p.occasion.toLowerCase()} outfit selected for a ${p.fit.toLowerCase()} silhouette.`,search_query:"",accessory:null,shirt:{...x.shirt,search_query:x.shirt.name},pant:{...x.pant,search_query:x.pant.name},shoes:{...x.shoes,search_query:x.shoes.name}})); }
function parse(raw){try{return JSON.parse(raw)}catch{} const m=String(raw||"").match(/\{[\s\S]*\}/);try{return m?JSON.parse(m[0]):null}catch{return null}}
const schema={type:"object",additionalProperties:false,properties:{looks:{type:"array",minItems:3,maxItems:3,items:{type:"object",additionalProperties:false,properties:{name:{type:"string"},emoji:{type:"string"},match:{type:"number"},style:{type:"string"},occasion:{type:"string"},fit:{type:"string"},total_price:{type:"number"},reason:{type:"string"},shirt:{type:"object",additionalProperties:false,properties:{name:{type:"string"},price:{type:"number"},search_query:{type:"string"}},required:["name","price","search_query"]},pant:{type:"object",additionalProperties:false,properties:{name:{type:"string"},price:{type:"number"},search_query:{type:"string"}},required:["name","price","search_query"]},shoes:{type:"object",additionalProperties:false,properties:{name:{type:"string"},price:{type:"number"},search_query:{type:"string"}},required:["name","price","search_query"]},accessory:{type:["object","null"],additionalProperties:false,properties:{name:{type:"string"},price:{type:"number"},search_query:{type:"string"}},required:["name","price","search_query"]}},required:["name","emoji","match","style","occasion","fit","total_price","reason","shirt","pant","shoes","accessory"]}}},required:["looks"]};
export default async function handler(req){ if(req.method!=="POST") return json({error:"Method not allowed"},405); let body={}; try{body=await req.json()}catch{return json({error:"Invalid request body"},400)} const p=prefs(body.preferences); const fallback=fallbackFor(p); if(!process.env.OPENAI_API_KEY) return json({configured:false,looks:fallback,source:"fallback"});
 const photo=typeof body.photoDataUrl==="string"&&body.photoDataUrl.startsWith("data:image/")?body.photoDataUrl:"";
 const prompt=`You are FITAI personal stylist. Create exactly 3 single complete outfits for this user. Style: ${p.style}. Occasion: ${p.occasion}. Fit: ${p.fit}. Colors: ${p.colors.join(",")||"flexible"}. Max budget INR ${p.budget}. Each outfit MUST have exactly one shirt/top, one pant/bottom, one pair of shoes, optional one accessory. No alternatives or piles of choices. Use broad visible clothing proportions only if an image is supplied; do not identify the person or infer sensitive traits. Keep every outfit within budget. Return only JSON matching the schema.`;
 const input=photo?[{role:"user",content:[{type:"input_text",text:prompt},{type:"input_image",image_url:photo}]}]:prompt;
 const controller=new AbortController(); const timer=setTimeout(()=>controller.abort(),7000);
 try{const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${process.env.OPENAI_API_KEY}`},signal:controller.signal,body:JSON.stringify({model:MODEL,input,max_output_tokens:1200,text:{format:{type:"json_schema",name:"fitai_outfits",strict:true,schema}})}); clearTimeout(timer); const data=await r.json().catch(()=>({})); if(!r.ok) throw new Error(data?.error?.message||`HTTP ${r.status}`); const raw=data.output_text||((data.output||[]).flatMap(x=>x.content||[]).map(x=>x.text||x.value||"").join("\n")); const parsed=parse(raw); if(!parsed?.looks||parsed.looks.length!==3) throw new Error("Invalid AI response"); return json({configured:true,looks:parsed.looks,source:"ai"});}catch(e){clearTimeout(timer); console.error("FITAI AI fallback:",e); return json({configured:true,looks:fallback,source:"fallback",note:"AI temporarily unavailable; instant styling fallback used."});} }
function fallbackFor(p){return fallback(p)}
