export const config = { runtime: "nodejs" };
const MODEL = process.env.FITAI_OPENAI_MODEL || "gpt-4.1-mini";
const json = (data, status=200) => new Response(JSON.stringify(data), {status, headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
const s=(v,d="")=>String(v??d).trim().slice(0,240);
function prefs(x={}){const b=Number(x.budget);return{style:s(x.quickStyle,x.styles?.[0]||"Streetwear"),occasion:s(x.quickOccasion,x.occasions?.[0]||"Casual"),fit:s(x.fit,"Relaxed"),colors:Array.isArray(x.colors)?x.colors.slice(0,3).map(v=>s(v)):[],budget:Number.isFinite(b)&&b>0?b:3000}}
function fallback(p){const sets=[{name:`${p.style} Essential`,emoji:"🖤",shirt:[`${p.colors[0]||"Black"} relaxed-fit cotton shirt`,750],pant:["Straight-fit black trousers",900],shoes:["Minimal white sneakers",850]},{name:`${p.style} Clean Fit`,emoji:"🤍",shirt:["Cream oversized textured shirt",850],pant:["Dark straight-fit jeans",950],shoes:["Black low-top sneakers",800]},{name:`${p.style} Statement Fit`,emoji:"🕶️",shirt:["Oversized graphic tee",650],pant:["Wide-leg cargo pants",950],shoes:["Retro chunky sneakers",900]}];return sets.map(x=>({...x,match:92,style:p.style,occasion:p.occasion,fit:p.fit,total_price:x.shirt[1]+x.pant[1]+x.shoes[1],reason:`A complete ${p.style} look for ${p.occasion.toLowerCase()} with a ${p.fit.toLowerCase()} silhouette.`,shirt:{name:x.shirt[0],price:x.shirt[1],search_query:x.shirt[0]},pant:{name:x.pant[0],price:x.pant[1],search_query:x.pant[0]},shoes:{name:x.shoes[0],price:x.shoes[1],search_query:x.shoes[0]},accessory:null})).map(x=>({...x,total_price:Math.min(x.total_price,p.budget)}))}
function parse(raw){try{return JSON.parse(raw)}catch{}const m=String(raw||"").match(/\{[\s\S]*\}/);try{return m?JSON.parse(m[0]):null}catch{return null}}
function item(v){if(!v)return{name:"",price:0,search_query:""};const name=s(v.name||v);return{name,price:Math.max(0,Number(v.price)||0),search_query:s(v.search_query,name)}}
function normalize(data,p){if(!Array.isArray(data?.looks)||data.looks.length!==3)return null;return data.looks.map((x,i)=>({name:s(x.name,`FITAI Look ${i+1}`),emoji:s(x.emoji,["🖤","🤍","🕶️"][i]),match:Math.max(70,Math.min(99,Number(x.match)||90)),style:s(x.style,p.style),occasion:s(x.occasion,p.occasion),fit:s(x.fit,p.fit),total_price:Math.min(Math.max(0,Number(x.total_price)||0),p.budget),reason:s(x.reason,"Matched to your preferences and proportions."),shirt:item(x.shirt),pant:item(x.pant),shoes:item(x.shoes),accessory:x.accessory?item(x.accessory):null}))}
export default async function handler(req){if(req.method!=="POST")return json({error:"Method not allowed"},405);let body={};try{body=await req.json()}catch{return json({error:"Invalid request body"},400)}const p=prefs(body.preferences);const instant=fallback(p);if(!process.env.OPENAI_API_KEY)return json({configured:false,source:"fallback",looks:instant});const photo=typeof body.photoDataUrl==="string"&&body.photoDataUrl.startsWith("data:image/")?body.photoDataUrl:"";const prompt=`You are FITAI, an expert Gen-Z personal stylist in India. Create exactly 3 complete outfits for the user. Style: ${p.style}. Occasion: ${p.occasion}. Preferred fit: ${p.fit}. Colors: ${p.colors.join(",")||"flexible"}. Maximum budget INR ${p.budget}. Each look MUST contain exactly one shirt/top, one pant/bottom and one pair of shoes, plus at most one accessory. No alternatives. If a photo is supplied, use only broad visible clothing proportions to choose flattering fits; never identify the person or infer sensitive traits. Return ONLY JSON: {"looks":[{"name":"","emoji":"","match":90,"style":"","occasion":"","fit":"","total_price":0,"reason":"","shirt":{"name":"","price":0,"search_query":""},"pant":{"name":"","price":0,"search_query":""},"shoes":{"name":"","price":0,"search_query":""},"accessory":null}]}`;const input=photo?[{role:"user",content:[{type:"input_text",text:prompt},{type:"input_image",image_url:photo}]}]:prompt;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),3200);try{const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${process.env.OPENAI_API_KEY}`},signal:controller.signal,body:JSON.stringify({model:MODEL,input,max_output_tokens:850})});clearTimeout(timer);const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data?.error?.message||`HTTP ${r.status}`);const raw=typeof data.output_text==="string"?data.output_text:((data.output||[]).flatMap(x=>x.content||[]).map(x=>x.text||x.value||"").join("\n"));const looks=normalize(parse(raw),p);if(!looks)throw new Error("Invalid AI response");return json({configured:true,source:"ai",looks})}catch(e){clearTimeout(timer);console.error("FITAI AI fallback",e);return json({configured:true,source:"fallback",looks:instant,note:"AI was slow or unavailable, so FITAI used instant styling."})}}
