export const config = { runtime: "nodejs" };
const MODEL = process.env.FITAI_OPENAI_MODEL || "gpt-4.1-mini";
const json = (data, status=200) => new Response(JSON.stringify(data), {status, headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
const s = (v,d="") => String(v ?? d).trim().slice(0,240);
function prefs(x={}) { const b=Number(x.budget); return {style:s(x.quickStyle,x.styles?.[0]||"Streetwear"),occasion:s(x.quickOccasion,x.occasions?.[0]||"Casual"),fit:s(x.fit,"Relaxed"),colors:Array.isArray(x.colors)?x.colors.slice(0,3).map(s):[],budget:Number.isFinite(b)&&b>0?b:3000}; }
function fallback(p){ const c=p.colors[0]||"Black"; const sets=[
{name:`${p.style} Essential`,emoji:"🖤",shirt:{name:`${c} relaxed-fit cotton shirt`,price:850},pant:{name:"Straight-fit black trousers",price:1050},shoes:{name:"Minimal white sneakers",price:900}},
{name:`${p.style} Clean Fit`,emoji:"🤍",shirt:{name:"Cream oversized textured shirt",price:950},pant:{name:"Dark straight-fit jeans",price:1100},shoes:{name:"Black low-top sneakers",price:850}},
{name:`${p.style} Statement Fit`,emoji:"🕶️",shirt:{name:"Oversized graphic tee",price:700},pant:{name:"Wide-leg cargo pants",price:1150},shoes:{name:"Retro chunky sneakers",price:1050}}]; return sets.map((x,i)=>({...x,match:94-i*3,style:p.style,occasion:p.occasion,fit:p.fit,total_price:Math.min(x.shirt.price+x.pant.price+x.shoes.price,p.budget),reason:`One complete ${p.style} ${p.occasion.toLowerCase()} outfit selected for a ${p.fit.toLowerCase()} silhouette.`,accessory:null,shirt:{...x.shirt,search_query:x.shirt.name},pant:{...x.pant,search_query:x.pant.name},shoes:{...x.shoes,search_query:x.shoes.name}})); }
function parse(raw){try{return JSON.parse(raw)}catch{} const m=String(raw||"").match(/\{[\s\S]*\}/);try{return m?JSON.parse(m[0]):null}catch{return null}}
function normalize(data,p){if(!Array.isArray(data?.looks)||data.looks.length!==3)return null;return data.looks.map((x,i)=>({...x,name:s(x.name,`FITAI Look ${i+1}`),emoji:s(x.emoji,["🖤","🤍","🕶️"][i]),match:Math.max(70,Math.min(99,Number(x.match)||90)),style:s(x.style,p.style),occasion:s(x.occasion,p.occasion),fit:s(x.fit,p.fit),total_price:Math.min(Math.max(0,Number(x.total_price)||p.budget),p.budget),shirt:item(x.shirt),pant:item(x.pant),shoes:item(x.shoes),accessory:x.accessory?item(x.accessory):null}));}
function item(v){if(!v)return{name:"",price:0,search_query:""};const name=s(v.name||v);return{name,price:Math.max(0,Number(v.price)||0),search_query:s(v.search_query,name)};}
export default async function handler(req){if(req.method!=="POST")return json({error:"Method not allowed"},405);let body={};try{body=await req.json()}catch{return json({error:"Invalid request body"},400)}const p=prefs(body.preferences);const instant=fallback(p);if(!process.env.OPENAI_API_KEY)return json({configured:false,looks:instant,source:"fallback"});
const photo=typeof body.photoDataUrl==="string"&&body.photoDataUrl.startsWith("data:image/")?body.photoDataUrl:"";const prompt=`You are FITAI personal stylist in India. Create exactly 3 complete outfits. Style: ${p.style}. Occasion: ${p.occasion}. Fit: ${p.fit}. Colors: ${p.colors.join(",")||"flexible"}. Max budget INR ${p.budget}. Each outfit MUST have exactly one shirt/top, one pant/bottom and one pair of shoes, optional one accessory. No alternatives. Keep every outfit within budget. If an image is supplied, use only broad visible clothing proportions; do not identify the person or infer sensitive traits. Return only JSON with a looks array.`;const input=photo?[{role:"user",content:[{type:"input_text",text:prompt},{type:"input_image",image_url:photo}]}]:prompt;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),5500);
try{const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${process.env.OPENAI_API_KEY}`},signal:controller.signal,body:JSON.stringify({model:MODEL,input,max_output_tokens:900})});clearTimeout(timer);const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data?.error?.message||`HTTP ${r.status}`);const raw=data.output_text||((data.output||[]).flatMap(x=>x.content||[]).map(x=>x.text||x.value||"").join("\n"));const looks=normalize(parse(raw),p);if(!looks)throw new Error("Invalid AI response");return json({configured:true,looks,source:"ai"});}catch(e){clearTimeout(timer);console.error("FITAI AI fallback:",e);return json({configured:true,looks:instant,source:"fallback",note:"AI unavailable; instant styling used."});}}
